### ISSUE TITLE
Add an ignored 'references' top-level key to allow for yaml placeholder usage

### ISSUE THREAD

**Issue by PeterJCLaw** [thread/routemaster#101]
Routemaster configs can get quite verbose and repetitive. It would be great to be able to convert something like this:
``` yaml
states:
- gate: first
  triggers:
    - time: 17h30m
      timezone: metadata.timezone
    - event: entry # for debug
  exit_condition: 12h has passed since history.entered_state or metadata.debug
  next: second

- gate: second
  triggers:
    - time: 17h30m
      timezone: metadata.timezone
    - event: entry # for debug
  exit_condition: 12h has passed since history.entered_state or metadata.debug
  next: third
```
into this
``` yaml
references:
  wait-one-day: &wait-one-day
    triggers:
      - time: 17h30m
        timezone: metadata.timezone
      - event: entry # for debug
    exit_condition: 12h has passed since history.entered_state or metadata.debug

states:
- gate: first
  <<: *wait-one-day
  next: second

- gate: second
  <<: *wait-one-day
  next: third
```

However I believe at the moment the config schema validation would reject this.
