### ISSUE TITLE
Validate top level feeds

### ISSUE THREAD

**Issue by PeterJCLaw** [thread/routemaster#45]
If you have a config like:
``` yaml
state_machines:
  the_workflow:
    feeds:
      - name: jacquard
        url: http://localhost:1212/<label_id>
    states:
      - gate: choice
        triggers:
          - event: entry
        exit_condition: true
        next:
          type: context
          path: jacquard.has_option_b
          default: option_a
          destinations:
            - value: true
              state: option_b

      - gate: option_a
        exit_condition: false

      - gate: option_b
        exit_condition: false
```

Then this looks valid and passes validation. However the `choice` gate doesn't work as expected since `jacquard` isn't a valid top-level path -- instead you need to use `feeds.jacquard.has_option_b`.

While we obviously can't validate the `has_option_b` part, we should be able to validate that:
* paths only start with one of the three valid options (`metadata`, `feeds` or `history`)
* `feeds` paths only start with a feed which is actually configured
