### ISSUE TITLE
Feed 404 causes LabelAlreadyExists error when creating a label

### ISSUE THREAD

**Issue by PeterJCLaw** [thread/routemaster#47]
If you have a config like:
``` yaml
state_machines:
  the_workflow:
    feeds:
      - name: jacquard
        url: http://localhost:1212/<label>
    states:
      - gate: choice
        triggers:
          - event: entry
        exit_condition: true
        next:
          type: context
          path: jacquard.has_option_b
          default: option_a
          destinations:
            - value: true
              state: option_b

      - gate: option_a
        exit_condition: false

      - gate: option_b
        exit_condition: false
```
which uses a feed in the exit of the first state, but that feed returns a 404 (likely because it's misconfigured, though that might also be a correct response), then the overall creation request will error with `LabelAlreadyExists`.
